name: ModInjector

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight UTC
  workflow_dispatch: # Allow manual runs

jobs:
  check_version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.check.outputs.new_version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r check-version-requirements.txt

      - name: Check for the latest version
        id: check
        run: |
          python check_version.py
      - name: Commit and push changes
        if: needs.check_version.outputs.new_version == 'true'
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Updated version.txt

  download_decrypted_ipa:
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.new_version == 'true'
    steps:
      - name: Debugging
        run: |
          echo "New version detected: ${{ needs.check_version.outputs.new_version }}"
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r download-ipa-requirements.txt

      - name: Download decrypted IPA
        run: python download_ipa.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

